controller:
  admin:
    username: admin
    password: admin
  serviceType: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.local
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - docker-workflow
  JCasC:
    defaultConfig: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
agent:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
