controller:
  kind: Deployment
  replicaCount: 1
  service:
    type: NodePort
  watchIngressWithoutClass: false
  admissionWebhooks:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
